# Generated by Django 2.2.4 on 2019-08-13 09:34

from django.db import migrations, models
import librairy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(db_index=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Album description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(db_index=True, max_length=42)),
                ('source_file', models.ImageField(storage=librairy.models.PictureFileSystemStorage(), upload_to=librairy.models.set_pathname)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('description', models.TextField(verbose_name='Picture description')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('pictures', models.ManyToManyField(blank=True, to='librairy.Picture')),
            ],
        ),
    ]
