# Generated by Django 2.2.4 on 2019-08-11 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import librairy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(db_index=True, max_length=42)),
                ('source_file', models.ImageField(storage=librairy.models.PictureFileSystemStorage(), upload_to=librairy.models.set_pathname)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('description', models.TextField(verbose_name='Picture description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('pictures', models.ManyToManyField(blank=True, to='librairy.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(db_index=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Album description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('pictures', models.ManyToManyField(blank=True, to='librairy.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='picture',
            index=models.Index(fields=['sha1', 'user'], name='librairy_pi_sha1_4a5329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('sha1', 'user')},
        ),
    ]
