# Generated by Django 2.2.4 on 2019-08-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0002_auto_20190813_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='original_name',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
