# Generated by Django 2.2.4 on 2019-08-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0003_picture_original_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
    ]
